export const PICS_REQUEST_START = 'PICS_REQUEST_START';
export const PICS_REQUEST_SUCCES = 'PICS_REQUEST_SUCCES';
export const PICS_REQUEST_ERROR = 'PICS_REQUEST_ERROR';

export const NEXT_PICS_REQUEST_SUCCES = 'NEXT_PICS_REQUEST_SUCCES';
